### ISSUE TITLE
curl hangs on h2c GET

### ISSUE THREAD

**Issue by icing** [bagder/curl#192] opened 2015-04-01 12:25 UTC
Testing mod_h2 with curl reduced my overall hair count over the last two days. Fortunately, it also made me learn things about tcpdump and wireshark,

The culprits:
```curl 7.42.0-DEV (x86_64-unknown-linux-gnu) libcurl/7.42.0-DEV OpenSSL/1.0.1f zlib/1.2.8 nghttp2/0.7.9``` and 
```curl 7.41.0 (x86_64-apple-darwin14.1.0) libcurl/7.41.0 OpenSSL/1.0.2a zlib/1.2.8 nghttp2/0.7.9```
with command line:
```curl -v  --http2 http://10.211.55.19:12345/index.html``` from osx to ubuntu and
```curl -v  --http2 http://10.211.55.2:12345/index.html``` from ubuntu to osx.

The client on OSX works fine as show in this wireshark shot:
![osx2ubuntu](https://cloud.githubusercontent.com/assets/15102/6940574/9c5736ee-d878-11e4-9f4c-37fc98d2b502.png)

The client on Ubuntu however does not send anything after the HTTP2 preface. Just silent, no ACK for the SETTINGS from the server:
![ubuntu2osx](https://cloud.githubusercontent.com/assets/15102/6940575/9c5ac58e-d878-11e4-9e4e-eed5e2d2547f.png)

At this point the connection just hangs as the server is unwilling to send the response before an ACK to the SETTINGS. Is there a flush missing somewhere maybe?

**Comment by bagder** [comment] 2015-04-01 12:47
Thanks! Can you repeat this problem against a public URL or do we need to run a local version of mod_h2?

**Comment by icing** [comment] 2015-04-01 12:50
One of these days I have to setup a public mod_h2 installation, but currently I do not have one. You could try to build the sandbox or wait until you are back from vacation. Now that I know the nature of the problem, I just disabled the affected test cases and can continue working.

**Comment by tatsuhiro-t** [comment] 2015-04-01 15:11
I tried mod_h2-0.4.2 with latest curl + nghttp2 both on debian machine, upgrade worked fine.
So probably, network between two machine or mac OS X related problem?

**Comment by icing** [comment] 2015-04-01 15:21
Well, unfortunately, it seems not so simple. I had the effect also when the client and server ran on the same ubuntu image. Only tcpdump did not work so nicely then. The problem was originally reported by another dev working on another ubuntu image.

It seems timing sensitive. The slower the machine (less CPU core, more detailed logging) the more often it happens. That is why I suspected some flush behaviour where the ACK frame lingers in some buffer somewhere....

The nghttp client always works in all my configurations. It's really the SETTINGS+ACK from the client to the server that is not happening and everything stalls. Or so I read it. I was on it the whole yesterday and today and my brain is a bit foggy...

**Comment by tatsuhiro-t** [comment] 2015-04-01 15:25
You are right, this is timing dependent.
While I'm reading curl code, I probably found the cause.
It is possible that curl does not send SETTINGS ACK if SETTINGS frame is received before curl sends MAGIC.  We have missing `nghttp2_session_send()` call in `Curl_http2_switched()`.
I'll make a PR for this soon...  Could you verify that whether it works?

**Comment by icing** [comment] 2015-04-01 15:28
Tatsuhiro-sama, that's it! The SETTINGS is indeed sent before the preface arrives. Champagne! :-D


> Am 01.04.2015 um 17:25 schrieb Tatsuhiro Tsujikawa <notifications@github.com>:
> 
> You are right, this is timing dependent.
> While I'm reading curl code, I probably found the cause.
> It is possible that curl does not send SETTINGS ACK if SETTINGS frame is received before curl sends MAGIC. We have missing nghttp2_session_send() call in Curl_http2_switched().
> I'll make a PR for this soon... Could you verify that whether it works?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

<green/>bytes GmbH
Hafenweg 16, 48155 Münster, Germany
Phone: +49 251 2807760. Amtsgericht Münster: HRB5782

**Comment by tatsuhiro-t** [comment] 2015-04-01 15:36
PR #194
I hope it works..

**Comment by icing** [comment] 2015-04-02 08:05
It works like a dream. All go for pull from my side.

**Comment by bagder** [comment] 2015-04-02 13:21
PR #194 has been merged, case closed!

**Closed by bagder** 2015-04-02 13:21 UTC
Labels: HTTP/2
