### ISSUE TITLE
cURL unstable transfer data when CPU high load other apps.

### ISSUE THREAD

**Issue by z0hm** [bagder/curl#347] opened 2015-07-15 16:32 UTC
WinXPSP2, cURL 7.43.
CPU load ~95-100% other apps with normal priority, cURL as is have normal priority. When curl transfer (curl -T filename) with SSL connection TLSv1.2 (from verbose) and other apps overload CPU to 95-100% - curl drop traffic and after disconnect (SSL_write() returned SYSCALL, errno=10053). If curl transfer more 90 min, then disconnect without overload CPU other apps - ~2-4% load CPU. cURL don't have buffer for transmit data or buffer size is very small?

**Comment by bagder** [comment] 2015-07-19 22:17
Buffer size is irrelevant as the kernel maintains the TCP connection completely without any buffer in user-space. I've not heard nor seen anyone else experience this problem. I think you've drawn the wrong conclusion and that the problem is not related to the CPU load of other applications but possibly that you have something in your network or server end that closes connections that are alive after 90 minutes.

**Comment by z0hm** [comment] 2015-07-20 09:31
Now ISP deal with the situation... Perhaps the remote server does not consistently

**Comment by bagder** [comment] 2015-07-20 10:09
Then let's close this now and re-open in the future in case you see it again and can reproduce.

**Closed by bagder** 2015-07-20 10:09 UTC
