### ISSUE TITLE
curl -z -o appears to be broken

### ISSUE THREAD

**Issue by tempoz** [bagder/curl#240] opened 2015-04-27 19:51 UTC
I updated curl on ArchLinux this morning, and my script which uses curl -z and -o appears to be broken. It now replaces the file passed to -o with an empty file if the file I ask for is older than the file I pass to -z, as opposed to the old behavior, which left the file passed to -o in place.

**Comment by jay** [comment] 2015-04-27 20:28
Thanks for your report. This is a duplicate of #237 and fixed in 7.43.1 which will be released this week.

**Comment by jay** [comment] 2015-04-27 20:29
s/7.43.1/7.42.1

**Closed by jay** 2015-04-27 20:28 UTC

**Comment by tempoz** [comment] 2015-04-27 20:33
Haha, thank you very much for your quick reply.
