### ISSUE TITLE
Doesn't reject invalid HTTP response

### ISSUE THREAD

**Issue by ianpark** [bagder/curl#467] opened 2015-10-01 16:19 UTC
Hi,

I am using libCur 7.42.1.1. While running Codenomicon with our http interface which is built with libCurl, I found something working ambiguous or wrong.

If peer sends back a dummy data like "aaaaaaaaaaaaaaa" without HTTP response result code or headers, the write function is called with the raw data. As far as I know the write function will be only called with HTTP response body so my code just stores on the buffer whatever given.

After then, The task is completed with CURLE_OK. How come it is OK when the response is not HTTP response. And the when I get the HTTP response code using get_easy_info, it returns 0.

So I put workaround fix:
1. check response code in the write function
2. if response code is 0, regard it as there were no HTTP header so handle it as a raw data or return 0 to reject the download.

What's more proper way to handle this case? How to reject if the response is not following HTTP standard. Why doesn't curl handle this case by checking the protocol and not calling write function at all?

I am not allowed to upload any pcap files so I attach a snapshot.

![aaa](https://cloud.githubusercontent.com/assets/4631393/10226616/7b3cf5ac-6860-11e5-9027-5ce58a59a28c.PNG)

**Comment by bagder** [comment] 2015-10-01 16:24
Isn't the title wrong? As you get a malformed response, but you want it rejected rather than passed on as data so "Doesn't reject invalid HTTP response" seems more appropriate to me?

But yes, it is on purpose. At least early on, like a decade or so ago, there were some servers that just didn't respond with any headers at all and just send back the payload at once and at some point someone (most likely me) thought we should handle that.

In this day and age, I think it is a bad idea to accept that and I would be all for making that stricter and simply reject responses that aren't compliant.

**Comment by ianpark** [comment] 2015-10-02 09:02
Thanks Badger, that's very quick and clear. I really appreciate it.

I agree with you about my title. Actually I was not 100% sure if it was supposed to be rejected. Because the result code was CURLE_OK. Just felt difficult and confused handling the cases the HTTP response code was zero. My server has been handling the case as "Critical Unexpected Error" with scary error log! :) So I will modify the title.

How about adding an option flag to easy handler to reject it? Probably for those who's using the behavior. 

Another question is, is there any smarter way to deal with this case?

**Comment by dfandrich** [comment] 2015-10-03 09:40
I wouldn't be too eager to remove this functionality. This is how normal HTTP/0.9 servers respond, and modern browsers still support this. It wouldn't surprise me if there were still lots of such servers around, especially in the embedded world.

**Comment by bagder** [comment] 2015-10-04 10:12
Well, I could agree to adding an option that specifically tells libcurl to stop accepting it (for applications that prefer libcurl to not accept that old legacy style HTTP) and we can then possibly at some point in the future switch the default value for it...

**Comment by bagder** [comment] 2015-10-04 10:12
But as this is working as intended, I'm closing this issue.

**Closed by bagder** 2015-10-04 10:12 UTC
Labels: HTTP
