### ISSUE TITLE
Erroneous debug text when paired with OpenSSL 1.0.2 

### ISSUE THREAD

**Issue by wahjava** [bagder/curl#219] opened 2015-04-15 09:23 UTC
When running `curl-7.41.0` on FreeBSD 10.1-RELEASE compiled with `openssl-1.0.2`, I get following erroneous debug messages:

```
λ curl -svv -o /dev/null 'https://www.freebsd.org/'
*   Trying 8.8.178.110...
*   Trying 2001:1900:2254:206a::50:0...
* Connected to www.freebsd.org (8.8.178.110) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /usr/local/share/certs/ca-root-nss.crt
  CApath: none
* TLSv1.2, TLS Unknown, Unknown (22):
} [5 bytes data]
* TLSv1.2, TLS handshake, Client hello (1):
} [512 bytes data]
* SSLv2, Unknown (22):
{ [5 bytes data]
* TLSv1.2, TLS handshake, Server hello (2):
{ [98 bytes data]
* SSLv2, Unknown (22):
{ [5 bytes data]
* TLSv1.2, TLS handshake, CERT (11):
{ [4469 bytes data]
* SSLv2, Unknown (22):
{ [5 bytes data]
* TLSv1.2, TLS handshake, Server key exchange (12):
{ [589 bytes data]
* SSLv2, Unknown (22):
{ [5 bytes data]
* TLSv1.2, TLS handshake, Server finished (14):
{ [4 bytes data]
* SSLv2, Unknown (22):
} [5 bytes data]
* TLSv1.2, TLS handshake, Client key exchange (16):
} [70 bytes data]
* SSLv2, Unknown (20):
} [5 bytes data]
* TLSv1.2, TLS change cipher, Client hello (1):
} [1 bytes data]
* SSLv2, Unknown (22):
} [5 bytes data]
* TLSv1.2, TLS handshake, Finished (20):
} [16 bytes data]
* SSLv2, Unknown (20):
{ [5 bytes data]
* TLSv1.2, TLS change cipher, Client hello (1):
{ [1 bytes data]
* SSLv2, Unknown (22):
{ [5 bytes data]
* TLSv1.2, TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; OU=Gandi Standard Wildcard SSL; CN=*.freebsd.org
*        start date: 2014-11-18 00:00:00 GMT
*        expire date: 2015-11-18 23:59:59 GMT
*        subjectAltName: www.freebsd.org matched
*        issuer: C=FR; ST=Paris; L=Paris; O=Gandi; CN=Gandi Standard SSL CA 2
*        SSL certificate verify ok.
* SSLv2, Unknown (23):
} [5 bytes data]
> GET / HTTP/1.1
> User-Agent: curl/7.41.0
> Host: www.freebsd.org
> Accept: */*
> 
* SSLv2, Unknown (23):
{ [5 bytes data]
< HTTP/1.1 200 OK
< Date: Sun, 05 Apr 2015 03:22:12 GMT
< Content-Type: text/html
< Transfer-Encoding: chunked
< Connection: keep-alive
< Last-Modified: Sun, 05 Apr 2015 03:10:15 GMT
< ETag: "5520a797-6f25"
< Server: ToTheCloud/v0.01
< X-Varnish: 1938974843 1938974183
< Age: 25
< Via: 1.1 wfe0.ysv.FreeBSD.org
< X-Cache: HIT
< Strict-Transport-Security: max-age=31536000; includeSubdomains
< 
{ [3820 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* SSLv2, Unknown (23):
{ [5 bytes data]
* Connection #0 to host www.freebsd.org left intact
```

As reported in the [original bug report](https://sourceforge.net/p/curl/bugs/1481/), it seems to happen on Windows as well.

Let us know if you need any other information.

Thanks!

**Comment by michael-o** [comment] 2015-04-29 09:45
I can confirm this on 9.3-STABLE with 7.42.0.

**Comment by bagder** [comment] 2015-05-04 10:32
Thanks, fix landed in 690317aae21d2b

**Closed by bagder** 2015-05-04 10:32 UTC
Labels: SSL/TLS

**Comment by michael-o** [comment] 2015-05-04 10:37
I will give it a try tomorrow.

**Comment by jay** [comment] 2015-05-05 05:14
Thanks for investigating and fixing this Daniel. Using OpenSSL 1.0.2a and curl commit 8a35211 2015-05-04 this is the output I get now in Windows Visual Studio 2010 configuration 'DLL Debug - DLL OpenSSL' (either Win32 or x64) when I connect to https://google.com:

```
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* STATE: SENDPROTOCONNECT => PROTOCONNECT handle 0x1e9f788; line 1210 (connection #0)
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
```

There is no [xx bytes of data] message any longer. I think it looks cleaner this way but I'm not sure if that's what you intended because there is still a colon at the end of each action line.

**Comment by bagder** [comment] 2015-05-05 06:02
Really? I don't see how this change could have that effect (and my unpatched 7.42.1 comparison output doesn't show any such "xx bytes of data" output). This change should only remove "unknown" lines and change the explanatory texts somewhat. Or have I missed something?

If you need the full details I'd say that --trace and --trace-ascii are the better options.

**Comment by jay** [comment] 2015-05-05 06:35
Nevermind I was comparing it against the OP's output instead of my own. I tried the commit before your changes and I don't get the [data] messages there either. Also I checked the sourceforge bug and I didn't get [data] there either.

**Comment by bagder** [comment] 2015-05-05 06:39
Ok, goodie. Then I wasn't hallucinating too badly! =)

**Comment by michael-o** [comment] 2015-05-05 07:51
Looks ok now:

    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /usr/local/share/certs/combined-ca.pem
      CApath: none
    * TLSv1.2 (OUT), TLS header, Certificate Status (22):
    } [5 bytes data]
    * TLSv1.2 (OUT), TLS handshake, Client hello (1):
    } [512 bytes data]
    * TLSv1.2 (IN), TLS handshake, Server hello (2):
    { [98 bytes data]
    * TLSv1.2 (IN), TLS handshake, Certificate (11):
    { [1873 bytes data]
    * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
    { [589 bytes data]
    * TLSv1.2 (IN), TLS handshake, Server finished (14):
    { [4 bytes data]
    * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
    } [70 bytes data]
    * TLSv1.2 (OUT), TLS change cipher, Client hello (1):
    } [1 bytes data]
    * TLSv1.2 (OUT), TLS handshake, Finished (20):
    } [16 bytes data]
    * TLSv1.2 (IN), TLS change cipher, Client hello (1):
    { [1 bytes data]
    * TLSv1.2 (IN), TLS handshake, Finished (20):
    { [16 bytes data]
    * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
    * ALPN, server did not agree to a protocol
    * Server certificate:
    
Is the colon referring to the byte data below? If not, I'd rather remove that.

**Comment by michael-o** [comment] 2015-05-05 08:33
Just checked on another OS with OpenSSL 0.9.8. It's fine too.
