### ISSUE TITLE
Cannot download from GitHub with curl 7.42.1 on Windows

### ISSUE THREAD

**Issue by michael-o** [bagder/curl#267] opened 2015-05-14 18:13 UTC
Running

    mosipov@MIKA /d/Projekte/curl ((curl-7_42_1))
    $ curl --version
    curl 7.42.1 (i386-pc-win32) libcurl/7.42.1 WinSSL
    Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtp
    telnet tftp
    Features: AsynchDNS Largefile SSPI Kerberos SPNEGO NTLM SSL
    
with

    curl https://github.com/michael-o/curl.git

gives me

    curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - 
    Das Format der empfangenen Nachricht war unerwartet oder fehlerhaft.

I have compiled this to solve [this](https://issues.apache.org/jira/browse/INFRA-9605) issue.

**Comment by jay** [comment] 2015-05-14 18:33
How did you build? I have `curl-7_42_1` checked out and I cannot reproduce. I was trying to reproduce a separate issue on Win2k and at one point I got an ILLEGAL_MESSAGE error but I figured it just something to do with protocol or algorithms disabled in Win2k.

In Windows 7 x64:
~~~
X:\j\curl\curl-LATEST\build\Win32\VC10\DLL Debug - DLL Windows SSPI - DLL WinIDN
>curld --version
curl 7.42.0-DEV (i386-pc-win32) libcurl/7.42.0-DEV WinSSL WinIDN
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp
smb smbs smtp smtps telnet tftp
Features: AsynchDNS Debug IDN Largefile SSPI Kerberos SPNEGO NTLM SSL

X:\j\curl\curl-LATEST\build\Win32\VC10\DLL Debug - DLL Windows SSPI - DLL WinIDN
>curld https://github.com/michael-o/curl.git
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
~~~

There is a problem with schannel in curl that I'm working on at #244 but I don't think it's related.

**Comment by michael-o** [comment] 2015-05-14 18:45
I have built with mingw, gcc 4.8.2, make 3.81 on Windows XP SP3.

**Comment by jay** [comment] 2015-05-14 18:58
Confirmed `SEC_E_ILLEGAL_MESSAGE` fail on XP x86 SP3 and XP x64 SP2. Vista/7/8 ok. Tested `curl-7_42_1` in configuration `DLL Debug - DLL Windows SSPI - DLL WinIDN | Win32` using Visual Studio 2010.

**Comment by michael-o** [comment] 2015-05-14 19:36
Thanks for the confirmation. I just opened up the GitHub URL in IE8, it won't load. So I guess we need to report this to GitHub directly. It does not seem to be a bug in curl.

**Comment by michael-o** [comment] 2015-05-14 19:39
Here is the confirmation: https://www.ssllabs.com/ssltest/analyze.html?d=github.com scroll down for "Handshake Simulation".

**Comment by jay** [comment] 2015-05-14 19:47
You might be SOL on this one. Github ciphers are all AES but [XP x86 does not support AES](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380512.aspx). XP x64 and Windows Server 2003 same thing but one difference, there's an [MS hotfix](https://support.microsoft.com/en-us/kb/948963) to add TLS_RSA_WITH_AES_256_CBC_SHA which is compatible with Github's servers.

**Comment by bagder** [comment] 2015-05-14 20:53
XP with "native" crypto is doomed to have lots of problems with the modern web already. I would strongly urge anyone still on XP to use a modern crypto library with support for updated cryptos so that you can speak with the ever growing part of the Internet that is using stricter TLS requirements.

**Comment by michael-o** [comment] 2015-05-14 21:09
@jay, do you think that we could make SSPI tell us that cipher could not be negotiated? The response now does not really help.

**Comment by jay** [comment] 2015-05-15 07:21
> do you think that we could make SSPI tell us that cipher could not be negotiated? The response now does not really help.

There's a mapping [here](https://msdn.microsoft.com/en-us/library/windows/desktop/dd721886.aspx) that shows for what TLS/SSL alerts schannel will return `SEC_E_ILLEGAL_MESSAGE`. I can't find in the schannel doc how to get the alert information. @mback2k any idea?
<br>

> I stumbled upon this while trying to access ASF Git repos. Curl fails over HTTP with TLS. Something is wrong/incomplete the the ca-bundle. I have even tried this one from master. No avail.

I doubt that has to do with the ca-bundle.

`git-wip-us.apache.org` sends the entire certificate chain to the client. You can see those certificates either in Wireshark or `openssl s_client -showcerts -connect git-wip-us.apache.org:443` or copy them from [here](http://www.networking4all.com/en/support/tools/site+check/report/?fqdn=git-wip-us.apache.org&protocol=https).

The root CA apache sends `VeriSign Class 3 Public Primary Certification Authority - G5` is different from [the certificate of the same name in the ca-bundle](https://github.com/bagder/ca-bundle/blob/bff056d/ca-bundle.crt#L1300-L1325). Both certificates have the same key and subject:

~~~
CN = VeriSign Class 3 Public Primary Certification Authority - G5
OU = (c) 2006 VeriSign, Inc. - For authorized use only
OU = VeriSign Trust Network
O = VeriSign, Inc.
C = US
~~~

The issuer for the ca-bundle one is the same as the subject, as one would expect. However check out the issuer for the one send by the apache website:
~~~
OU = Class 3 Public Primary Certification Authority
O = VeriSign, Inc.
C = US
~~~
:(

If I make a bundle with just these two:
`Symantec Class 3 Secure Server CA - G4`
`VeriSign Class 3 Public Primary Certification Authority - G5` (the ca-bundle one)
I can use it to successfully verify the server certificate:

~~~
cat "VeriSign from mozilla bundle.cer" "Symantec from git-wip-us.apache.org.cer" > both.cer
openssl verify -CAfile both.cer -verbose -purpose any "Server - git-wip-us.apache.org.cer"
Server - git-wip-us.apache.org.cer: OK
~~~

Try with the VeriSign one sent by the server and it fails...
~~~
C = US, O = "VeriSign, Inc.", OU = VeriSign Trust Network, OU = "(c) 2006 VeriSign, Inc. - For authorized use only", CN = VeriSign Class 3 Public Primary Certification Authority - G5
error 2 at 2 depth lookup:unable to get issuer certificate
~~~

So my guess is OpenSSL is setup to work so that the CA sent by the server trumps any preloaded.

Certificates also available [here](https://gist.github.com/jay/dd18b10a0b24aa0c626d) if you're unable to reproduce.

**Comment by michael-o** [comment] 2015-05-15 09:08
> There's a mapping here that shows for what TLS/SSL alerts schannel will return SEC_E_ILLEGAL_MESSAGE. I can't find in the schannel doc how to get the alert information.

Great, they map half a dozen of errors to one. :-1: ...Microsoft...

**Comment by stumped2** [comment] 2015-05-15 16:59
@jay is there anything I can change on ASF's webserver end to help with this?

When I got the cert from Symantec, that was the intermediate cert they said to use. But if there's something I can change, let me know and I can get a mock ssl site up for testing.

**Comment by jay** [comment] 2015-05-15 19:25
@stumped2 If you want to support both legacy clients (using the 2021 VeriSign cert) and newer clients (using the 2036 VeriSign cert) it looks like you'd have to supply the 2021 for legacy clients assuming they don't have it *(remember 2021 is an intermediate and 2036 isn't)*, as you're currently doing. You may be able to change the ordering so that OpenSSL will handle it differently. This is a rare case where it actually may help to include a self-signed root CA in a chain file just to manipulate the ordering, but I don't know if that's acceptable.

For example if I order it so the 2036 is before the 2021:
~~~
cat "VeriSign from mozilla bundle.cer" "VeriSign from git-wip-us.apache.org.cer" "Symantec from git-wip-us.apache.org.cer" > three.cer
openssl verify -CAfile three.cer -verbose -purpose any "Server - git-wip-us.apache.org.cer"
~~~

But will that work client side when they have certificates that are preloaded? And will that break legacy clients? You'd have to setup a server to test all scenarios. If it were me I'd probably remove the 2021 version from the chain file (I assume [`SSLCertificateChainFile`](http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#SSLCertificateChainFile) or similar) and see who protests.

I don't see anything wrong with the Symantec intermediate. If Symantec gave you the chain file I suggest you take it up with them. If you look at [their CA root advisory page](http://www.symantec.com/page.jsp?id=roots) you can see it specifies the 2036 version of the VeriSign certificate (the one in the Mozilla ca-bundle) not the 2021. 2021 version goes back to 'Class 3 Public Primary Certification Authority' which is an old certificate that uses md2 as signature hash and md2 has been disabled for a long while in OpenSSL, GnuTLS. Also see https://ssltest2.bbtest.net/ . There's a nice explanation on the difference between the two VeriSign certs [here](http://www.confusedamused.com/notebook/fixing-verisign-certificates-on-windows-servers/).

**Comment by stumped2** [comment] 2015-05-15 19:29
Thanks @jay! I'll read up on this over the weekend and test some things out.

**Comment by jay** [comment] 2015-05-16 04:39
@michael-o I found that Windows XP has a sha1RSA version of [Class 3 Public Primary Certification Authority](https://gist.github.com/jay/dd18b10a0b24aa0c626d#file-verisign-legacy-ca-sha1rsa-cer). You should be able to use it as the CA file until this issue is resolved. Tested:
~~~
curl -v --cacert "VeriSign legacy CA - sha1RSA.cer" "https://git-wip-us.apache.org/repos/asf?p=flex-utilities.git"
~~~
~~~
curl 7.39.0 (i386-pc-win32) libcurl/7.39.0 OpenSSL/1.0.0r zlib/1.2.8 libidn/1.18
 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp
rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN Largefile SSPI SPNEGO NTLM SSL libz
~~~

**Comment by mback2k** [comment] 2015-05-19 20:55
@jay I don't know about any way to access the alert code using the SCannel APIs. According to [this MSDN blog post](http://blogs.msdn.com/b/kaushal/archive/2012/10/06/ssl-tls-alert-protocol-amp-the-alert-codes.aspx) the alert information is written to the system event log. This means it might be possible to extract that information from there. I think that would probably be quite fragile.

**Comment by jay** [comment] 2015-05-19 21:19
Thanks for checking Marc, unfortunately I agree. I think the best I can do here is in [`Curl_sspi_strerror`](https://github.com/bagder/curl/blob/265f83a/lib/strerror.c#L800) append some text to the detail for `SEC_E_ILLEGAL_MESSAGE` that says something like "For error detail enable Schannel EventLogging in Windows." That way at least the user will know more detail can be made available in the event log.

**Comment by michael-o** [comment] 2015-05-20 18:02
@jay, @mback2k, I was not able to get that message in the event log. I have enabled debug logging on Windows XP with the value `0x3` and called curl against GitHub. No avail.

Is there anything one needs to observe?

**Comment by jay** [comment] 2015-05-20 19:15
> I was not able to get that message in the event log. I have enabled debug logging on Windows XP with the value 0x3 and called curl against GitHub. No avail.

@michael-o more bad news for you. Empirical testing just now shows a lack of recorded alert messages to the System event log, particularly in the case of `SEC_E_ILLEGAL_MESSAGE`. This is not specific to curl; I get the same behavior with IE. (side note: some versions of IE may fallback to TLS 1.0 in case of `SEC_E_ILLEGAL_MESSAGE` and may make a successful connection depending on the server, but not in your case).

I'm not sure what the criteria is for recording alert messages, I can't find it documented. I tried  several servers where the client hello causes a return of alert `SSL3_ALERT_UNEXPECTED_MESSAGE` (10) instead of a sever hello, but it no case does it show in my logs. I cannot find any evidence that alert is recorded client-side though some web searches show [it can be recorded server-side](http://forums.iis.net/t/1168770.aspx). I tried Windows XP, 7 and 8. I could see in Wireshark that the alert was sent back always when I expected. I have all logging enabled (warn, error, info) for Schannel.

If you want to test if Schannel error logging is working (I doubt this is the problem though) try https://kuix.de:9455/ . You should see error `TLS1_ALERT_UNKNOWN_CA` (48) recorded in the event log.

So we're back where we were yesterday. The only other thing I can think of is we parse it out of the recv data, but that seems like it would be a lot of work and personally I don't think it's worthwhile. I'm strongly leaning towards closing this by having a helpful error message accompany `SEC_E_ILLEGAL_MESSAGE`, and that's all.

**Comment by michael-o** [comment] 2015-05-20 19:25
> So we're back where we were yesterday. The only other thing I can think of is we parse it out of the recv data, but that seems like it would be a lot of work and personally I don't think it's worthwhile. I'm strongly leaning towards closing this by having a helpful error message accompany SEC_E_ILLEGAL_MESSAGE, and that's all.

All I can do here is: agree. Microsoft gives us, again, pain in the ass. SSPI is too high-level for this.

**Comment by michael-o** [comment] 2015-05-20 19:27
@jay, maybe we could add [here](http://curl.haxx.se/docs/ssl-compared.html) another row showing that that TLS impl gives reasonable messages back.

**Comment by jay** [comment] 2015-05-22 06:42
I changed the description for `SEC_E_ILLEGAL_MESSAGE` in 995c600. Here is an example of what the output looks like now:
~~~
curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAG
E (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is receive
d (e.g. handshake failed). More detail may be available in the Windows System ev
ent log.
~~~
I'm limited to about 200 characters so I can't add anything else to the text.

> maybe we could add here another row showing that that TLS impl gives reasonable messages back

@michael-o I don't think that's necessary, the new error message should be enough.

**Closed by jay** 2015-05-22 06:42 UTC
Labels: SSL/TLS

**Comment by mback2k** [comment] 2015-05-24 07:15
Thanks a lot, @jay.

**Comment by jay** [comment] 2018-03-25 02:55
> Github ciphers are all AES but XP x86 does not support AES. XP x64 and Windows Server 2003 same thing but one difference, there's an MS hotfix to add TLS_RSA_WITH_AES_256_CBC_SHA which is compatible with Github's servers.

An update on this, I've found github is still accessible with a fully updated Windows XP SP3 x86 with the POSReady key (the hack you can use to still receive security updates in XP). At some point in the last several months they updated the schannel for TLS 1.1 and TLS 1.2 support. Also contrary to my assertion that XP x86 doesn't support AES it does. I have snapshots from last year that are using AES.

Here's a ClientHello from curl 7.60.0-DEV w/schannel July 2017 updates snapshot:
~~~
    TLSv1 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.0 (0x0301)
        Length: 80
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 76
            Version: TLS 1.0 (0x0301)
            Random: 5ab70966941566189188d67646aad9e72543442142604546...
                GMT Unix Time: Mar 24, 2018 22:28:54.000000000 Eastern Daylight Time
                Random Bytes: 941566189188d67646aad9e72543442142604546a0c0e9fd...
            Session ID Length: 0
            Cipher Suites Length: 26
            Cipher Suites (13 suites)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)
                Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
                Cipher Suite: TLS_RSA_WITH_DES_CBC_SHA (0x0009)
                Cipher Suite: TLS_RSA_EXPORT1024_WITH_RC4_56_SHA (0x0064)
                Cipher Suite: TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA (0x0062)
                Cipher Suite: TLS_RSA_EXPORT_WITH_RC4_40_MD5 (0x0003)
                Cipher Suite: TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 (0x0006)
                Cipher Suite: TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x0013)
                Cipher Suite: TLS_DHE_DSS_WITH_DES_CBC_SHA (0x0012)
                Cipher Suite: TLS_DHE_DSS_EXPORT1024_WITH_DES_CBC_SHA (0x0063)
            Compression Methods Length: 1
            Compression Methods (1 method)
                Compression Method: null (0)
            Extensions Length: 9
            Extension: extended_master_secret (len=0)
                Type: extended_master_secret (23)
                Length: 0
            Extension: renegotiation_info (len=1)
                Type: renegotiation_info (65281)
                Length: 1
                Renegotiation Info extension
                    Renegotiation info extension length: 0
~~~

and here's a ClientHello from curl 7.60.0-DEV w/schannel March 2018 updates snapshot:
~~~
    TLSv1.2 Record Layer: Handshake Protocol: Client Hello
        Content Type: Handshake (22)
        Version: TLS 1.2 (0x0303)
        Length: 90
        Handshake Protocol: Client Hello
            Handshake Type: Client Hello (1)
            Length: 86
            Version: TLS 1.2 (0x0303)
            Random: 5ab708eb95b8ef97a43f4680f9d0105a81ab46b3d86fb3f1...
                GMT Unix Time: Mar 24, 2018 22:26:51.000000000 Eastern Daylight Time
                Random Bytes: 95b8ef97a43f4680f9d0105a81ab46b3d86fb3f137ac7d1f...
            Session ID Length: 0
            Cipher Suites Length: 20
            Cipher Suites (10 suites)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA256 (0x003d)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003c)
                Cipher Suite: TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
                Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA (0x002f)
                Cipher Suite: TLS_RSA_WITH_RC4_128_MD5 (0x0004)
                Cipher Suite: TLS_RSA_WITH_RC4_128_SHA (0x0005)
                Cipher Suite: TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000a)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x006a)
                Cipher Suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x0040)
                Cipher Suite: TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x0013)
            Compression Methods Length: 1
            Compression Methods (1 method)
                Compression Method: null (0)
            Extensions Length: 25
            Extension: signature_algorithms (len=12)
                Type: signature_algorithms (13)
                Length: 12
                Signature Hash Algorithms Length: 10
                Signature Hash Algorithms (5 algorithms)
                    Signature Algorithm: rsa_pkcs1_sha256 (0x0401)
                        Signature Hash Algorithm Hash: SHA256 (4)
                        Signature Hash Algorithm Signature: RSA (1)
                    Signature Algorithm: rsa_pkcs1_sha384 (0x0501)
                        Signature Hash Algorithm Hash: SHA384 (5)
                        Signature Hash Algorithm Signature: RSA (1)
                    Signature Algorithm: rsa_pkcs1_sha1 (0x0201)
                        Signature Hash Algorithm Hash: SHA1 (2)
                        Signature Hash Algorithm Signature: RSA (1)
                    Signature Algorithm: SHA1 DSA (0x0202)
                        Signature Hash Algorithm Hash: SHA1 (2)
                        Signature Hash Algorithm Signature: DSA (2)
                    Signature Algorithm: rsa_pkcs1_sha512 (0x0601)
                        Signature Hash Algorithm Hash: SHA512 (6)
                        Signature Hash Algorithm Signature: RSA (1)
            Extension: extended_master_secret (len=0)
                Type: extended_master_secret (23)
                Length: 0
            Extension: renegotiation_info (len=1)
                Type: renegotiation_info (65281)
                Length: 1
                Renegotiation Info extension
                    Renegotiation info extension length: 0
~~~

Background [here](https://support.microsoft.com/en-us/help/4019276/update-to-add-support-for-tls-1-1-and-tls-1-2-in-windows). It seems to imply some registry keys need to be set to enable TLS 1.1 and 1.2 but I did not need to set those keys and they aren't set in the registry.
