### ISSUE TITLE
Static Linking to openssl does not work.

### ISSUE THREAD

**Issue by Deli-Zhang** [bagder/curl#567] opened 2015-12-15 08:43 UTC
Reproduction steps
1. Build openssl 1.0.2d to static library and install to folder /root/openssl_xxx
    # ls /root/openssl_xxx/lib/ 
    engines  libcrypto.a  libssl.a  pkgconfig
    #
    You can see only .a files here.
2. Build libcurl 7.43.0 and static link to openssl
    # ./configure --with-ssl=/root/openssl_xxx --without-zlib
    # make
    The so is generated at ./lib/.libs/libcurl.so
3. Check the relocation information of libcurl.so
    # readelf -r lib/.libs/libcurl.so | grep SSL
    ...
    Relocation section '.rel.plt' at offset 0x86cc4 contains 307 entries:
    Offset     Info    Type            Sym.Value  Sym. Name
    ...
    0022244c  000ead07 R_386_JUMP_SLOT   000ec790   SSL_connect
    0022246c  000ef107 R_386_JUMP_SLOT   000ecc08   SSL_free
    00222478  000f4807 R_386_JUMP_SLOT   000eaf78   SSL_CTX_set_default_pa
    00222484  000f8407 R_386_JUMP_SLOT   000e9508   SSL_get_peer_certifica
    00222494  000fa807 R_386_JUMP_SLOT   000ec200   SSL_get_verify_result
    002224e8  0010c307 R_386_JUMP_SLOT   000e9554   SSL_get_peer_cert_chai
    00222510  00110307 R_386_JUMP_SLOT   000e9864   SSL_write
    ...

    You can see all openssl symbols are PLT type.

    If a process loaded another different openssl library (e.g. 0.9.8) before libcurl.so,
    then all openssl symbol will be linked dynamically into 0.9.8 version. 
    # readelf -d test_curl
    ...
    0x00000001 (NEEDED)                     Shared library: [libssl.so.0.9.8]
    ...
    0x00000001 (NEEDED)                     Shared library: [libcurl.so.4]
    ...

    Because 0.9.8 and 1.0.2 are incompatible, thus process may crash.

**Comment by bagder** [comment] 2015-12-15 09:14
I claim this is not because of curl or curl's configure, but because of something you did when you built it. I regularly build with a static openssl library and I never experience any problems.

Like for example curl 7.43.0 still required manually providing "-ldl" in LDFLAGS for the configure check to work (commit a284b0ebc fixed that and was first released in 7.44.0), and you didn't specify it?

**Comment by Deli-Zhang** [comment] 2015-12-16 03:30
I think the issue has nothing to do with -ldl.

My configure is just below:
# ./configure --with-ssl=/root/openssl_xxx --without-zlib

and I checked libcurl.so asm code:
#  objdump -S ./lib/.libs/libcurl.so.4.3.0 | grep CRYPTO_free
   c61b1:	e8 22 1c fc ff       	call   87dd8 <CRYPTO_free@plt>
   c637d:	e8 56 1a fc ff       	call   87dd8 <CRYPTO_free@plt>
you can find the call method is CRYPTO_free@plt,
thus if process has loaded another openssl, like previous example, openssl 0.9.8 before libcurl.so,
then the process will call into openssl 0.9.8's CRYPTO_free, instead of libcurl.so with static openssl 1.0.2.

The actual libcurl.so of static linking to openssl should like below:
#  objdump -S libcurl.so.4.good_static | grep CRYPTO_free
   76131:	e8 c2 e2 03 00       	call   b43f8 <CRYPTO_free>
   762fd:	e8 f6 e0 03 00       	call   b43f8 <CRYPTO_free>
you can see calling and linking address for CRYPTO_free is only in module libcurl.so itself.

**Comment by bagder** [comment] 2015-12-16 09:37
I don't understand. What are you saying the problem is?

**Comment by MoSal** [comment] 2015-12-16 11:20
I think @Deli-Zhang has two openssl versions installed. An old system one with a shared libraries.
And a new one where static-only libraries are available. He wants to build against the new static ones.

He managed to build with the new headers. But curl seems to have linked against the old shared libraries.

@Deli-Zhang 
The full linker commands that were run are necessary for us to know why that happened.

**Comment by nasacj** [comment] 2015-12-18 02:36
Hi @bagder , I am trying to build a curl binary static link to openssl (libssl.a), how can I configure the build?
>
export PKG_CONFIG_PATH=....
export LDFLAGS=-L....

But I get the error:
``` shell
  CCLD     libcurl.la
/usr/lib64/gcc/x86_64-suse-linux/4.1.2/../../../../x86_64-suse-linux/bin/ld: /home/p_jdcjqian/projects/openssl-1.0.2e_bin/lib/libssl.a(s2_clnt.o): relocation R_X86_64_32 against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/home/p_jdcjqian/projects/openssl-1.0.2e_bin/lib/libssl.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
```
There is only static lib file in openssl-1.0.2e_bin/lib/

**Comment by nasacj** [comment] 2015-12-18 03:23
https://github.com/bagder/curl/issues/503
``` shell
LDFLAGS="-static" PKG_CONFIG="pkg-config --static" ./configure --disable-shared --enable-static
make curl_LDFLAGS=-all-static
```
can solve my problem

**Comment by Deli-Zhang** [comment] 2015-12-18 05:01
If some one build curl with static openssl library, he must wish openssl api calling by curl should link into the static openssl library. 
e.g. in some curl function CRYPTO_free will be called, but how do you ensure CRYPTO_free will be linked or relocated to the static openssl library by ld.so when the process running.
If we did not ensure this, ld.so may relocate the symbol to other openssl library if there is multi openssl library in process address space.
This issue is related to ld.so, so we should ensure real static openssl linked to avoid the problem.

Below is real static linking. when curl call CRYPTO_free, the symbol address b43f8  is just in libcurl.so scope.
# objdump -S libcurl.so.4.good_static | grep CRYPTO_free
76131: e8 c2 e2 03 00 call b43f8 <CRYPTO_free>

But below is not real static linking, because when CRYPTO_free is called, ld.so will lookup global symbol table in all the process depends libraries. so once ld.so found a same CRYPTO_free symbol in another version openssl library(e.g. 0.9.8) before the static openssl library (1.0.2)within libcurl, ld.so will link to the former (0.9.8)
# objdump -S ./lib/.libs/libcurl.so.4.3.0 | grep CRYPTO_free
c61b1: e8 22 1c fc ff call 87dd8 <CRYPTO_free@plt>

**Comment by bagder** [comment] 2015-12-18 07:08
@Deli-Zhang : I understand what static linking is, I build curl against a static OpenSSL several times a day. I just don't understand what you're saying the error in configure or the build scripts is.

I build a static curl against a static OpenSSL built from their git repo like this:

~~~~
LIBS="-ldl -lpthread" ./configure --disable-shared --with-ssl=$HOME/build-openssl

**Comment by Deli-Zhang** [comment] 2015-12-20 15:53
[test_issue.tar.gz](https://github.com/bagder/curl/files/67841/test_issue.tar.gz)
I write a tiny example to illustrate the issue.
libxxx.so defines a function say_hi(),
libzzz.a defines another function say_hi() too.
in libyyy.so function call_say_hi() calls say_hi(), and libyyy.so links the static library libzzz.a,
Thus we must expect the main process prints "zzz: Hi!" once call_say_hi() executed.
But the test results are uncertain due to different methods of compile and link for libyyy.so and main.
# ./build.sh 
r - zzz.o
-----------------------
main: Hi! 
zzz: Hi! 
-----------------------
main: Hi! 
xxx: Hi! 
-----------------------
main: Hi! 
xxx: Hi! 
-----------------------
main: Hi! 
xxx: Hi!

libxxx.so stands for openssl 0.9.8
libzzz.a stands for openssl 1.0.2
libyyy.so stands for libcurl.so 

So libcurl should ensure libcurl.so calls the static openssl functions no matter how user compiles his main program and link libcurl.so.

**Comment by Deli-Zhang** [comment] 2015-12-20 16:13
I have found a solution to build libyyy.so:
```
gcc -g -I. -shared -fPIC xxx.c -o libxxx.so

gcc -g -I. -shared -fPIC -c zzz.c -o zzz.o
ar rvs libzzz.a zzz.o

gcc -g -I. -shared -fPIC -L. -Wl,--version-script=yyy.map  \
    -Wl,--whole-archive -lzzz -Wl,-no-whole-archive yyy.c -o libyyy.so

gcc -g -I. -L. -lxxx -lyyy main.c -o main
./main
```
yyy.map file is like below 
```
# cat yyy.map 
yyy {
	global: call_say_hi;
	local: *;
};
```

I tested on RHEL4.7, it's always OK.
And I don't know whether there is other or even simpler solutions, please just refer to it.

**Comment by bagder** [comment] 2015-12-20 19:23
I still don't see how this is a curl issue. It is a matter of building and linking correctly. But I'm glad it works for you now.

**Closed by bagder** 2015-12-20 19:23 UTC
Labels: build, SSL/TLS

**Comment by Deli-Zhang** [comment] 2015-12-21 01:45
If it's not curl issue, could you please tell me how to specify this two options when I configure curl?
```
-Wl,--version-script=yyy.map
-Wl,--whole-archive -lzzz -Wl,-no-whole-archive
```

I have ever tried to set with LDFLAGS and LIBS, but curl configure does not work following my expect.

**Comment by bagder** [comment] 2015-12-21 07:16
I would imagine that setting those options by default for LDFLAGS would confuse configure greatly. You can possibly get "make LDFLAGS=blablabla" work, but I suspect you may need something more handcrafted for such a setup to work.

**Comment by Deli-Zhang** [comment] 2015-12-21 08:56
OK I see.

**Comment by martingalvan** [comment] 2017-12-26 22:40
2 years later I just stumbled upon this same issue. Where is the LIBS="-ldl -lpthread" part documented? Also, why are we using -lpthread instead of pthread, other than to squelch the warning about LIBS being only for stuff that starts with '-l'?

**Comment by jay** [comment] 2017-12-27 04:21
@martingalvan I concur with @bagder here I don't see how this is a curl issue. It sounds like the reporter's build initially didn't actually build with a static openssl which is what caused his problems. It's not clear how that happened.

Whether we should use -pthread or -lpthread I see it usually as -lpthread, and I don't know why we have references to -pthread. I suspect -pthread may be used for legacy reasons, but I don't think it's needed.

**Comment by martingalvan** [comment] 2017-12-27 13:37
I didn't say it was a curl issue, I just said it doesn't seem to be documented anywhere (which, on the other hand, can be interpreted as a curl documentation issue). If it's documented somewhere, could you please point it out?

**Comment by DeliZhangX** [comment] 2017-12-27 14:15
The issue is that all openssl symbols are global visible although openssl library is linked into libcurl statically, one usually hopes  openssl symbols to be just local, which will bring benefit of avoiding link problem if there exists multi openssl libraries in process space.

**Comment by jay** [comment] 2017-12-27 19:26
> If it's documented somewhere, could you please point it out?

I don't know that it is. The configure script does not find the dependencies for static libraries, however in the special case of OpenSSL there is detection for -ldl and -lpthread here https://github.com/curl/curl/blob/curl-7_57_0/configure.ac#L1634-L1690

if it is not working please file a report

**Comment by martingalvan** [comment] 2017-12-27 20:27
It doesn't seem to be working, since it won't link unless I manually add LIBS="...". Looks like it hasn't worked for a while, since @bagder was using that LIBS="..." thing 2 years ago.

No need to file a report; this is the report :)

**Comment by MarcelRaad** [comment] 2017-12-29 08:56
The detection for -ldl and -lpthread is not working for me because of https://github.com/curl/curl/issues/2199: The OpenSSL lib is not passed to the linker in the tests.
