### ISSUE TITLE
Ignore optional client certificate request on HTTPS connection with curl/NSS

### ISSUE THREAD

**Issue by marconfus** [bagder/curl#540] opened 2015-11-24 10:45 UTC
Unfortunately, on RedHat Enterprise Linux curl is using NSS as the TLS framework. I noticed that this combination is not behaving like curl with OpenSSL.
If you are connecting to a server that has optional client certificate authentication, but you have no client cert, curl throws the error:
curl: (35) NSS: client certificate not found (nickname not specified)
Using curl with OpenSSL with the same server works fine as it just ignores the request for a client certificate.
As the RHEL provided NSS testclient also has no problem connecting to the server, I guess this should be fixed in curl.

**Comment by bagder** [comment] 2015-11-24 11:59
Seems like a logical conclusion. Any chance you can try to produce a patch for this? The check in question that probably needs adjustment seems to be here: https://github.com/bagder/curl/blob/master/lib/vtls/nss.c#L1065

**Comment by marconfus** [comment] 2015-11-24 13:03
I just found out, that just compiling the git master version of curl with RedHat provided NSS fixes the problem because "* NSS: client certificate not found (nickname not specified)" now is just a warning and not a fatal error.

RedHat uses:
# curl -V
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.18 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
Protocols: tftp ftp telnet dict ldap ldaps http file https ftps scp sftp 
Features: GSS-Negotiate IDN IPv6 Largefile NTLM SSL libz 

Do you have any idea where this changed? Perhaps I can convince RedHat to backport this :-)

**Comment by marconfus** [comment] 2015-11-24 13:18
OK, I think I have to look a little deeper into it. After a modification of the server config, I suddenly can't reproduce the error. Perhaps the root of the problem is somewhere else...

**Comment by bagder** [comment] 2015-11-24 13:49
If you can't reproduce it, then I think we'll close this until you can reproduce it - and hopefully that won't happen! =) Also, by all accounts 7.19.7 is oooold and we will urge you to upgrade rather than chase for problems is that old code base. We have fixed hundreds of bugs since. Thanks!

**Closed by bagder** 2015-11-24 13:49 UTC
Labels: SSL/TLS

**Comment by marconfus** [comment] 2015-11-24 14:11
Ok, this was an obscure problem with RedHat's version of curl where it makes a difference if you have a 2048 or 4096 bit serverkey. 2048 bit -> warning, 4096 bit -> fatal error. Sorry for any inconvenience and blaming your code...

**Comment by kdudka** [comment] 2015-11-24 14:26
I see no relevant difference in curl code between those versions. Both of them return ```SECFailure``` from ```SelectClientCert()``` in case a client certificate can not be loaded.  It is up to NSS itself how it handles failures coming out of the ```SelectClientCert()``` hook.  So you should better check versions of nss* packages.

@bagder Despite the RHEL-6 packages of curl are based on curl-7.19.7, many bug fixes from later upstream versions have been included over the time.  Namely the code specific to NSS is very close to latest upstream and the code of ```SelectClientCert()``` is **identical** up to white-space changes.

**Comment by bagder** [comment] 2015-11-24 14:33
Right, I was a bit brief. I don't mean to belittle the work you do to backport things and keep the redhat versions working, you're doing an impressive work there and I didn't mean to imply anything else. It's just that we as a project we really can't handle problems in older versions the way Redhat manages to maintain the older versions so to get the project members on their toes to fix things a recipe on how to reproduce in a modern version will have much higher chances of getting attention.

**Comment by marconfus** [comment] 2015-11-24 14:37
Yes, upgrading both curl and nss packages on RHEL6 fixed the problem. I just saw the line
```return SECFailure;```
in the latest curl code, so I wrongfully thought it's a curl problem.

**Comment by patrikhson** [comment] 2016-07-12 14:49
Hi,

I guess I found something really useful for you, take a look, you won't regret <http://steslowintu.facadepromo.com/xyfbso>

Later, paf@frobbit.se

**Comment by GinoPane** [comment] 2017-07-06 12:09
Hey guys! 
Is it possible to fix this issue without upgrading of curl?

**Comment by pbgarima** [comment] 2018-01-01 13:01
Can u please how to get client certificate
