### ISSUE TITLE
CURLOPT_TIMEOUT includes time waiting for connection

### ISSUE THREAD

**Issue by WGH-** [bagder/curl#437] opened 2015-09-16 16:33 UTC
Not sure if it's intended, but consider the following scenario.

A lot of easy handles have been added to the multi handle. Due to maximum connection limit, most of them are pending for connection. Curl hasn't tried to resolve the hostname, or connect, or anything. 

There is also a CURLOPT_TIMEOUT set. Since the timeout is calculated at the moment it's added to the multi handle (`multi_runsingle -> Curl_pretransfer -> Curl_expire` ), transfers somewhere at the end of the queue will be expired before libcurl has any chance to do anything on them.

I don't think timing out pending transfers is a good behaviour.

I can write a test case if necessary.

**Comment by bagder** [comment] 2015-09-16 22:01
I will agree that it isn't made crystal clear in the documentation on how a waiting transfer is supposed to act. However: to me the CURLOPT_TIMEOUT option is about setting the maximum time you allow a transfer/handle to spend trying to complete its mission and if it doesn't finish it in time, it returns. It is the total time you allow. To me, that then doesn't really matter exactly in what state the transfer is or isn't. You set the cut-off time and libcurl adheres to that cut-off time.

If it didn't work like that, you could have a transfer take longer than CURLOPT_TIMEOUT and that would be weird too!

**Comment by WGH-** [comment] 2015-09-17 10:18
I think additional timeout setting for actual transfer (that is, not counting being in waiting for connection state) would make sense and be useful, though. Like we already have CURLOPT_CONNECTTIMEOUT.

**Comment by bagder** [comment] 2015-09-18 11:54
Possibly, sure. I can't think of any easy way to make such a timeout work today with the callbacks we offer.

**Comment by bagder** [comment] 2015-09-25 11:29
Since this is not a bug, I'm closing this issue.

**Closed by bagder** 2015-09-25 11:29 UTC
Labels: enhancement
